# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:41
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='music',
            field=smartfields.fields.FileField(upload_to='music/'),
        ),
    ]
