# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:25
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_auto_20170626_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='music',
            field=smartfields.fields.FileField(upload_to='music/'),
        ),
    ]
